In [2]:
import torch

In [3]:
torch.__version__

'2.5.1+cpu'

In [4]:
import numpy as np

In [5]:
lst = [3,4,5,6]
arr = np.array(lst)
print(arr)

[3 4 5 6]


## Convert Numpy to Pytorch Tensors

In [6]:
tensors = torch.from_numpy(arr)
tensors

tensor([3, 4, 5, 6])

In [7]:
## Indexing similar to numpy
tensors[:2]

tensor([3, 4])

In [8]:
## Disadvantage of from_numpy. The array and tensor uses the same memory location
tensors[3]=100

In [9]:
tensors

tensor([  3,   4,   5, 100])

In [10]:
arr

array([  3,   4,   5, 100])

In [11]:
## Prevent this by using torch.tensor()
tensor_arr = torch.tensor(arr)
tensor_arr[3]=200
print(tensor_arr)
print(arr)

tensor([  3,   4,   5, 200])
[  3   4   5 100]


In [12]:
## zeros and ones
torch.zeros(2,3,dtype=torch.float64)

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [13]:
torch.ones(2,3,dtype=torch.float64)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [14]:
a=torch.tensor(np.arange(0,15).reshape(5,3))

In [17]:
a[:,0:2]

tensor([[ 0,  1],
        [ 3,  4],
        [ 6,  7],
        [ 9, 10],
        [12, 13]])

## Arithmetic Operations

In [19]:
a = torch.tensor([3,4,5], dtype=torch.float64)
b = torch.tensor([6,7,8], dtype=torch.int16)
print(a+b)

tensor([ 9., 11., 13.], dtype=torch.float64)


In [20]:
torch.add(a,b)

tensor([ 9., 11., 13.], dtype=torch.float64)

In [26]:
c=torch.ones(4)

In [27]:
torch.add(a,b,out=c)

C:\Users\Hp\AppData\Local\Temp\ipykernel_5128\3773876854.py:1: UserWarning: An output with one or more elements was resized since it had shape [4], which does not match the required output shape [3]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\Resize.cpp:35.)
  torch.add(a,b,out=c)


tensor([ 9., 11., 13.])

In [28]:
c

tensor([ 9., 11., 13.])

In [29]:
torch.add(a,b).sum()

tensor(33., dtype=torch.float64)

## Dot Products and Mult Operations

In [30]:
x=torch.tensor([1,2,3],dtype=torch.float64)
y=torch.tensor([4,5,6],dtype=torch.float64)

In [31]:
x.mul(y)

tensor([ 4., 10., 18.], dtype=torch.float64)

In [33]:
## 1*4 + 2*5 + 3*6
x.dot(y)

tensor(32., dtype=torch.float64)

## Matrix Multiplication

In [38]:
x=torch.tensor([[1,2,3],[1,5,5]],dtype=torch.float64)
y=torch.tensor([[5,7],[8,6],[3,4]],dtype=torch.float64)

In [39]:
torch.matmul(x,y)

tensor([[30., 31.],
        [60., 57.]], dtype=torch.float64)

In [40]:
torch.mm(x,y)

tensor([[30., 31.],
        [60., 57.]], dtype=torch.float64)

In [41]:
x@y

tensor([[30., 31.],
        [60., 57.]], dtype=torch.float64)